/* $Id$ */

#ifndef __GUI_H__
#define __GUI_H__

#define GUI_HELP_ABOUT 100
#define GUI_BUTTON_START 101
#define GUI_BUTTON_STOP 102
#define GUI_BUTTON_ABOUT 103
#define GUI_STATUS 104
#define GUI_TEWI_ICON 105
#define GUI_TEWI_NAME 106
#define GUI_TEWI_ORIGINAL 107
#define GUI_TEWI_DATE 108
#define GUI_LOG 109
#define GUI_BUTTON_EXIT 110
#define GUI_BUTTON_RESET 111
#define GUI_TEWI_WEBSITE 112

#define TIMER_WATCH_TEWI 1000

#endif
